# Generated by Django 5.0.2 on 2024-03-12 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tv_shows',
            name='notes',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
